### ISSUE TITLE
Deserialisation does not use JsonSerializerSettings

### ISSUE THREAD

**Issue by cwmiomni** [advancedrei/PortableRest#51]
In RestClient.cs, line 404, the call to DeserializeObject is not including the JsonSerializerSettings attached to restRequest:

    return JsonConvert.DeserializeObject<T>(responseContent);

looks like it should be

    return JsonConvert.DeserializeObject<T>(responseContent, restRequest.JsonSerializerSettings);

I'm seeing this express as a bug where the custom settings I use for TypeNameHandling or SerializationBinder are being ignored.

Just tried this change on a cloned copy and it fixed the problem.

**Comment by matteocontrini** [comment]
There's a pending pull request which should fix that... https://github.com/jeffijoe/PortableRest/commit/51e84b28c5e2bacd75babe494baa4ffafcf5e867

**Comment by jeffijoe** [comment]
@matteocontrini waiting to get it merged.. Looks like it won't happen.

**Comment by advancedrei** [comment]
I believe this change is in version 3.1.0-Beta1 on NuGet right now, but if it isn't, it will be in a new build posted this weekend. It's fixed, so I'm going to go ahead and close this.
