### ISSUE TITLE
Getting "Error getting value from 'ReadTimeout' on 'System.IO.FileStream'" when using AddFileParameter

### ISSUE THREAD

**Issue by jerriep** [advancedrei/PortableRest#57]
I am using the new AddFileParameter to read a file from disk using FileStream, but when I try and make an HTTP POST, I get a "Error getting value from 'ReadTimeout' on 'System.IO.FileStream'" exception.

It seems that it is because it is trying to serialize everything to a string and pass it using a `StringContent` object. 

I do not think this is the correct approach. For multipart data your should pass a `MultipartFormDataContent` instance.

Do you have an example of how to do file uploads with PortableRest, because I might just be missing something...

**Comment by advancedrei** [comment]
I didn't integrate the PR properly, and missed a section of the code that dealt with preparing the content for transfer. My bad. I've pushed Beta 2a to NuGet, try that one and see if it works.

**Comment by jerriep** [comment]
It is working now, thanks :)
