### ISSUE TITLE
Can you make the GetResourceUri method public?

### ISSUE THREAD

**Issue by jerriep** [advancedrei/PortableRest#59]
Hey Robert,

I would like to piggy-back off your GetResourceUri method to create the proper URLs for `/authorize` endpoint in the Auth0 Authentication client. Could you please make this method `public`, or is there a specific reason why you kept it `internal`?

https://github.com/advancedrei/PortableRest/blob/master/src/PortableRest/RestRequest.cs#L242-L263

**Comment by advancedrei** [comment]
I think it's internal partly because it is totally dependent on PortableRest internals, and I hadn't intended on it being called externally. Can you post a snippet of how you were thinking of using it? There might be another way to handle what you're wanting to do.

**Comment by jerriep** [comment]
So for the `/authorize` end points (https://auth0.com/docs/auth-api#!#get--authorize_social) I need to build up a URL and return it to the user. There is no actual call we need to make, we just need to build up a URL from the parameters and then pass it on to the user so they can make the actual call in the context of their application, because they will need to handle the 302 returned from that API endpoint.

So instead of me building up the URL and having to check for encoding parameters etc, correctly I wanted to just piggy-back off of you, e.g.:

```
public class AuthenticationApiClient : IAuthenticationApiClient
{
    private readonly Uri baseUri;

    public AuthenticationApiClient(Uri baseUri)
    {
        this.baseUri = baseUri;
    }

    public Task<Uri> BuildAuthorizationUri(BuildAuthorizationUriRequest request)
    {
        RestRequest restRequest = new RestRequest("authorize");
        restRequest.AddQueryString("response_type", request.ResponseType);
        restRequest.AddQueryString("client_id", request.ClientId);
        // etc.

        // And then...
        return restRequest.GetResourceUri(baseUri);
    }
}
```

This is my `BuildAuthorizationUriRequest` class:
```
public class BuildAuthorizationUriRequest
{
    public string ClientId { get; set; }
    public string Connection { get; set; }
    public Uri RedirectUri { get; set; }
    public AuthorizationResponseType ResponseType { get; set; }
    public string Scope { get; set; }
    public string State { get; set; }
}
```
Makes sense?

**Comment by advancedrei** [comment]
Yep, makes sense. There is a new build on NuGet: Beta3. Should work for you. Thanks!

**Comment by jerriep** [comment]
Awesome, thanks :D :+1: :+1: :+1:
