### ISSUE TITLE
Overridding ExecuteAsync and SendAsync

### ISSUE THREAD

**Issue by johnamcruz** [advancedrei/PortableRest#63]
Can you make the two methods above as virtual so that i can override it. I would like to call custom code before the base executeAsync is called.

**Comment by robertmclaws** [comment]
Can you tell me more about the issue that you're having that would require you to do so?

Thanks!

**Comment by johnamcruz** [comment]
I would like to AWS authorization (see below) to the header. The header info, url info and other required parameters are not available from the request. Also, I have an existing RestAPI client so overriding the executeAsync and SendAsync would allow to update all of it at once.

https://gist.github.com/yvanin/0bdf68c1139ad698519e 

I am currently calling ExecuteAsync the below

 var client = ClientFactory.Create(BaseUrl);
 var request = RequestFactory.Create(Resource, HttpMethod.Post);            
 request.AddParameter(item);            
 await client.ExecuteAsync<TModel>(request);

**Comment by johnamcruz** [comment]
Ignore my request. What I ended up doing is creating a custom http client handler that overrides the SendAsync method. I added the authorization there.

**Comment by robertmclaws** [comment]
That's a great solution! If you don't mind posting the code, or some pseudocode, I'd love to add it to the docs I'm working on.

Thanks!

**Comment by johnamcruz** [comment]
Here is the code Rob. 

https://gist.github.com/johnamcruz/d92e4754b5d6660ddfae9f6054e55a7d
https://gist.github.com/johnamcruz/07073c484add92479bf6fa777f11d375
